services:
  api:
    container_name: core-api
    image: api:1.0
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src_server:/app/src_server
    env_file:
      - .env
    environment:
      MONGO_URI: "mongodb://mongo:27017/mydatabase"
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
